<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>SeaculumFerrum</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <name>MCUniversalis</name>


    <repositories>
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>extendedclip-repo</id>
            <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>dynmap-repo</id>
            <url>https://repo.mikeprimm.com/</url>
        </repository>
        <repository>
            <id>citizens-repo</id>
            <url>https://repo.citizensnpcs.co/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot</artifactId>
            <version>1.18-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.TownyAdvanced</groupId>
            <artifactId>Towny</artifactId>
            <version>0.99.0.7</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.TownyAdvanced</groupId>
            <artifactId>Dynmap-Towny</artifactId>
            <version>0.85</version>
        </dependency>
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.11.6</version>
            <scope>system</scope>
            <systemPath>${basedir}/lib/PlaceholderAPI-2.11.6.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>23.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>us.dynmap</groupId>
            <artifactId>dynmap-api</artifactId>
            <version>2.5</version>
        </dependency>
        <dependency>
            <groupId>net.citizensnpcs</groupId>
            <artifactId>citizensapi</artifactId>
            <version>2.0.28-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.mcmonkey</groupId>
            <artifactId>sentinel</artifactId>
            <version>2.9.2-SNAPSHOT</version>
            <type>jar</type>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-platform-bukkit</artifactId>
            <version>4.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>4.4</version>
        </dependency>
        <dependency>
            <groupId>com.github.budgettoaster</groupId>
            <artifactId>religionlab</artifactId>
            <version>1.0.2</version>
            <scope>system</scope>
            <systemPath>${basedir}/lib/ReligionLab-1.0.2-all.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.maxgamer</groupId>
            <artifactId>Quickshop</artifactId>
            <version>5.1.2.0</version>
            <scope>system</scope>
            <systemPath>${basedir}/lib/QuickShop-5.1.2.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>io.github.townyadvanced</groupId>
            <artifactId>Eventwar</artifactId>
            <version>0.0.67</version>
            <scope>system</scope>
            <systemPath>${basedir}/lib/EventWar-0.0.67.jar</systemPath>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <artifactSet>
                        <includes>
                            <include>net.kyori:adventure-platform-bukkit</include>
                            <include>net.kyori:adventure-platform-api</include>
                            <include>net.kyori:adventure-api</include>
                            <include>net.kyori:adventure-text-serializer-craftbukkit</include>
                            <include>net.kyori:adventure-platform-facet</include>
                            <include>net.kyori:adventure-text-serializer-gson</include>
                            <include>net.kyori:adventure-text-serializer-legacy</include>
                            <include>net.kyori:adventure-key</include>
                            <include>net.kyori:adventure-text-serializer-gson-legacy-impl</include>
                            <include>net.kyori:adventure-text-serializer-bungeecord</include>
                            <include>net.kyori:adventure-platform-viaversion</include>
                            <include>net.kyori:adventure-nbt</include>
                            <include>org.apache.commons:commons-collections4</include>
                        </includes>
                    </artifactSet>
                    <relocations>
                        <relocation>
                            <pattern>net.kyori.adventure</pattern>
                            <shadedPattern>com.palmergames.adventure</shadedPattern>
                        </relocation>
                    </relocations>
                    <minimizeJar>true</minimizeJar>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

</project>