# SEACULUM FERRUM CONFIG(VER0.1) (Love from ♡Palaiologos_F♡)
# ========================================================================================
# This Config is not sufficient enough, and I will make some complements in the future.
# ========================================================================================


# =Basic Settings=

